export const ENV = {
  WEBSOCKET_URL: process.env.NEXT_PUBLIC_WEBSOCKET_URL,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  COGNITO_USER_POOL_ID: process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID,
  COGNITO_CLIENT_ID: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
};
